Importing important libraries

In [1]:
import pandas as pd
import numpy as np

Loading the dataset

In [2]:
df = pd.read_csv(r"D:\Guvi\Mini-project-2(Luxuary housing sales analysis)\House_analysis\Docs\Luxury_Housing_Bangalore.csv")
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

Check the column names

In [3]:
df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [5]:
df.shape

(101000, 18)

Check the null values

In [6]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

Removing duplicate values

In [7]:
df.duplicated(subset="Property_ID").sum()

np.int64(1000)

In [8]:
df[df.duplicated("Property_ID")]

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
100000,PROP036224,DOMLUR,Project_223,Embassy,4608.0,5bhk+,6.567529360287568,Secondary,HNI,2024-09-30,8.810723,8.286767,Launch,Broker,yes,9.291593,74,NaN
100001,PROP018298,Domlur,Project_297,Tata Housing,7455.0,5BHK+,NaN,Primary,Other,2024-12-31,4.173285,8.759681,Launch,Online,yes,8.447694,28,Great view from 15th floor.
100002,PROP084496,rajajinagar,Project_495,Prestige,3778.0,4bhk,12.568326856995945,Secondary,NRI,2023-12-31,9.366757,9.049776,Under construction,Broker,no,9.806097,92,Excellent location!
100003,PROP065620,DOMLUR,Project_119,Brigade,NaN,4BHK,₹12.59 Cr,Secondary,Startup Founder,2024-12-31,7.266646,5.718584,Launch,NRI Desk,yes,5.206301,88,Too far from my office.
100004,PROP088229,WHITEFIELD,Project_228,Total Environment,7458.0,4BHK,13.713149406825654,Secondary,HNI,2023-09-30,7.539427,7.310738,Ready to move,Direct,yes,6.533569,69,Connectivity is poor.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [9]:
df.drop_duplicates(subset='Property_ID', inplace=True)

In [10]:
df.duplicated(subset='Property_ID').sum()

np.int64(0)

Filling the Null values

First we should know about datatypes

In [11]:
df["Unit_Size_Sqft"].dtype

dtype('float64')

In [12]:
df["Ticket_Price_Cr"].dtype

dtype('O')

In [13]:
df["Amenity_Score"].dtype

dtype('float64')

cleaning the "Ticket_price_cr" column

In [14]:
df["Ticket_Price_Cr"] = df["Ticket_Price_Cr"].astype(str).str.replace("₹","").str.replace(" Cr","")

convert to numeric

In [15]:
df["Ticket_Price_Cr"] = pd.to_numeric(df["Ticket_Price_Cr"], errors="coerce")

In [16]:
df["Ticket_Price_Cr"].dtype

dtype('float64')

In [17]:
df["Amenity_Score"].fillna(df["Amenity_Score"].mean(),inplace=True)

drop the unnecessary column

In [18]:
df.drop("Buyer_Comments",axis=1,inplace=True)

Handling Invalid Values and filling the missing values

In [19]:
df.loc[df["Unit_Size_Sqft"] == -1, "Unit_Size_Sqft"] = np.nan

In [20]:
df["Unit_Size_Sqft"].fillna(df["Unit_Size_Sqft"].median(), inplace=True)

In [21]:
df["Unit_Size_Sqft"].describe()

count    100000.000000
mean       6005.247410
std        1638.257026
min        3000.000000
25%        4683.000000
50%        6004.000000
75%        7332.000000
max        8999.000000
Name: Unit_Size_Sqft, dtype: float64

In [22]:
df.loc[df["Ticket_Price_Cr"] < 0, "Ticket_Price_Cr"] = np.nan

In [23]:
df["Ticket_Price_Cr"].fillna(df["Ticket_Price_Cr"].median(), inplace=True)

In [24]:
df["Ticket_Price_Cr"].describe()

count    100000.000000
mean         12.652246
std           7.282516
min           0.660000
25%          10.265189
50%          12.038619
75%          13.832409
max         100.000000
Name: Ticket_Price_Cr, dtype: float64

In [25]:
df.isnull().sum()

Property_ID             0
Micro_Market            0
Project_Name            0
Developer_Name          0
Unit_Size_Sqft          0
Configuration           0
Ticket_Price_Cr         0
Transaction_Type        0
Buyer_Type              0
Purchase_Quarter        0
Connectivity_Score      0
Amenity_Score           0
Possession_Status       0
Sales_Channel           0
NRI_Buyer               0
Locality_Infra_Score    0
Avg_Traffic_Time_Min    0
dtype: int64

Normalize text fields

In [26]:
df["Developer_Name"].unique()

array(['RMZ', 'Puravankara', 'Tata Housing', 'Embassy', 'SNN Raj',
       'Brigade', 'Prestige', 'Total Environment', 'Godrej', 'L&T Realty',
       'Sobha'], dtype=object)

In [27]:
df["Micro_Market"].nunique()

48

In [28]:
df["Micro_Market"].unique()

array(['Sarjapur Road', 'Indiranagar', 'Bannerghatta Road',
       'bellary road', 'Koramangala', 'YELAHANKA', 'whitefield',
       'sarjapur road', 'JP NAGAR', 'Rajajinagar', 'koramangala',
       'WHITEFIELD', 'indiranagar', 'jayanagar', 'Whitefield', 'DOMLUR',
       'yelahanka', 'Mg Road', 'HENNUR ROAD', 'Jayanagar', 'Domlur',
       'Electronic City', 'Hebbal', 'mg road', 'jp nagar',
       'BANNERGHATTA ROAD', 'MG ROAD', 'KANAKAPURA ROAD', 'HEBBAL',
       'BELLARY ROAD', 'electronic city', 'ELECTRONIC CITY',
       'Bellary Road', 'Hennur Road', 'rajajinagar', 'Kanakapura Road',
       'INDIRANAGAR', 'hennur road', 'kanakapura road', 'domlur',
       'bannerghatta road', 'RAJAJINAGAR', 'hebbal', 'Yelahanka',
       'SARJAPUR ROAD', 'KORAMANGALA', 'Jp Nagar', 'JAYANAGAR'],
      dtype=object)

In [29]:
df["Micro_Market"] = df["Micro_Market"].str.strip().str.title()

In [30]:
df["Micro_Market"].unique()

array(['Sarjapur Road', 'Indiranagar', 'Bannerghatta Road',
       'Bellary Road', 'Koramangala', 'Yelahanka', 'Whitefield',
       'Jp Nagar', 'Rajajinagar', 'Jayanagar', 'Domlur', 'Mg Road',
       'Hennur Road', 'Electronic City', 'Hebbal', 'Kanakapura Road'],
      dtype=object)

In [31]:
df["Micro_Market"].nunique()

16

In [32]:
df["Developer_Name"] = df["Developer_Name"].str.strip().str.title()

In [33]:
df["Developer_Name"].nunique()

11

Feature extraction

Price_per_Sqft column

In [34]:
df["Price_per_Sqft"] = (df["Ticket_Price_Cr"] * 10000000) / df["Unit_Size_Sqft"]

In [35]:
df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Price_per_Sqft'],
      dtype='object')

In [36]:
df["Price_per_Sqft"] = df["Price_per_Sqft"].round(2)

In [37]:
df.Price_per_Sqft

0        31679.12
1        28284.99
2        13646.98
3        15175.01
4        21471.10
           ...
99995    18351.70
99996    38700.98
99997    24522.56
99998    14116.03
99999    20764.79
Name: Price_per_Sqft, Length: 100000, dtype: float64

In [38]:
df[df["Price_per_Sqft"] < 0]

Empty DataFrame
Columns: [Property_ID, Micro_Market, Project_Name, Developer_Name, Unit_Size_Sqft, Configuration, Ticket_Price_Cr, Transaction_Type, Buyer_Type, Purchase_Quarter, Connectivity_Score, Amenity_Score, Possession_Status, Sales_Channel, NRI_Buyer, Locality_Infra_Score, Avg_Traffic_Time_Min, Price_per_Sqft]
Index: []

In [39]:
df["Price_per_Sqft"].describe()

count    100000.000000
mean      22917.029997
std       15430.395655
min         995.620000
25%       15626.127500
50%       20051.000000
75%       26533.872500
max      324359.390000
Name: Price_per_Sqft, dtype: float64

Quarter column

In [40]:
df.Purchase_Quarter

0        2025-03-31
1        2024-06-30
2        2023-12-31
3        2024-03-31
4        2024-12-31
            ...
99995    2023-12-31
99996    2023-12-31
99997    2023-09-30
99998    2024-09-30
99999    2024-09-30
Name: Purchase_Quarter, Length: 100000, dtype: object

In [41]:
df["Purchase_Quarter"] = pd.to_datetime(df["Purchase_Quarter"])

In [42]:
df.Purchase_Quarter

0       2025-03-31
1       2024-06-30
2       2023-12-31
3       2024-03-31
4       2024-12-31
           ...
99995   2023-12-31
99996   2023-12-31
99997   2023-09-30
99998   2024-09-30
99999   2024-09-30
Name: Purchase_Quarter, Length: 100000, dtype: datetime64[ns]

In [43]:
df["Quarter"] = "Q" + df["Purchase_Quarter"].dt.quarter.astype(str)

In [44]:
df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Price_per_Sqft', 'Quarter'],
      dtype='object')

In [45]:
df.Quarter

0        Q1
1        Q2
2        Q4
3        Q1
4        Q4
         ..
99995    Q4
99996    Q4
99997    Q3
99998    Q3
99999    Q3
Name: Quarter, Length: 100000, dtype: object

In [46]:
df.shape

(100000, 19)

In [47]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Price_per_Sqft,Quarter
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,31679.12,Q1
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,4.839024,7.504185,Under construction,NRI Desk,no,7.723898,106,28284.99,Q2
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,13646.98,Q4
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,15175.01,Q1
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4Bhk,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,21471.10,Q4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,Bellary Road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193,Primary,NRI,2023-12-31,8.379908,7.504185,Under construction,Online,yes,8.378800,109,18351.70,Q4
99996,PROP099997,Yelahanka,Project_496,L&T Realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,4.716304,6.374069,Launch,Broker,yes,7.025209,20,38700.98,Q4
99997,PROP099998,Rajajinagar,Project_497,Prestige,5599.0,4BHK,13.730179,Primary,Startup Founder,2023-09-30,6.193347,7.482473,Launch,NRI Desk,yes,8.984990,63,24522.56,Q3
99998,PROP099999,Indiranagar,Project_498,Snn Raj,7342.0,4bhk,10.363989,Primary,NRI,2024-09-30,9.435646,6.369276,Under construction,NRI Desk,yes,7.634717,89,14116.03,Q3
99999,PROP100000,Hennur Road,Project_499,Embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,5.786292,5.284026,Launch,Broker,yes,6.039943,95,20764.79,Q3

Booking Flag column

In [48]:
df["Booking_Flag"] = df["Transaction_Type"].map({"Primary": 1, "Secondary": 0})

In [49]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Price_per_Sqft,Quarter,Booking_Flag
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,31679.12,Q1,1
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,4.839024,7.504185,Under construction,NRI Desk,no,7.723898,106,28284.99,Q2,1
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,13646.98,Q4,1
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,15175.01,Q1,1
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4Bhk,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,21471.10,Q4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,Bellary Road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193,Primary,NRI,2023-12-31,8.379908,7.504185,Under construction,Online,yes,8.378800,109,18351.70,Q4,1
99996,PROP099997,Yelahanka,Project_496,L&T Realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,4.716304,6.374069,Launch,Broker,yes,7.025209,20,38700.98,Q4,0
99997,PROP099998,Rajajinagar,Project_497,Prestige,5599.0,4BHK,13.730179,Primary,Startup Founder,2023-09-30,6.193347,7.482473,Launch,NRI Desk,yes,8.984990,63,24522.56,Q3,1
99998,PROP099999,Indiranagar,Project_498,Snn Raj,7342.0,4bhk,10.363989,Primary,NRI,2024-09-30,9.435646,6.369276,Under construction,NRI Desk,yes,7.634717,89,14116.03,Q3,1
99999,PROP100000,Hennur Road,Project_499,Embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,5.786292,5.284026,Launch,Broker,yes,6.039943,95,20764.79,Q3,1

Booking Status column

In [50]:
df["Booking_Status"] = df["Booking_Flag"].map({1:"Booked",0:"Not Booked"})

In [51]:
df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Price_per_Sqft', 'Quarter', 'Booking_Flag',
       'Booking_Status'],
      dtype='object')

In [52]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Price_per_Sqft,Quarter,Booking_Flag,Booking_Status
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,...,5.462863,Launch,Broker,yes,9.212491,18,31679.12,Q1,1,Booked
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,...,7.504185,Under construction,NRI Desk,no,7.723898,106,28284.99,Q2,1,Booked
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,...,8.669227,Ready to move,Direct,yes,6.985493,113,13646.98,Q4,1,Booked
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,5.720246,Ready to move,Online,yes,6.100929,106,15175.01,Q1,1,Booked
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4Bhk,15.345392,Secondary,HNI,2024-12-31,...,8.609649,Under construction,Broker,no,5.312510,18,21471.10,Q4,0,Not Booked
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,Bellary Road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193,Primary,NRI,2023-12-31,...,7.504185,Under construction,Online,yes,8.378800,109,18351.70,Q4,1,Booked
99996,PROP099997,Yelahanka,Project_496,L&T Realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,...,6.374069,Launch,Broker,yes,7.025209,20,38700.98,Q4,0,Not Booked
99997,PROP099998,Rajajinagar,Project_497,Prestige,5599.0,4BHK,13.730179,Primary,Startup Founder,2023-09-30,...,7.482473,Launch,NRI Desk,yes,8.984990,63,24522.56,Q3,1,Booked
99998,PROP099999,Indiranagar,Project_498,Snn Raj,7342.0,4bhk,10.363989,Primary,NRI,2024-09-30,...,6.369276,Under construction,NRI Desk,yes,7.634717,89,14116.03,Q3,1,Booked
99999,PROP100000,Hennur Road,Project_499,Embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,...,5.284026,Launch,Broker,yes,6.039943,95,20764.79,Q3,1,Booked

Booking Count column

In [53]:
df["Booking_Count"] = df["Booking_Flag"]

In [54]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Price_per_Sqft,Quarter,Booking_Flag,Booking_Status,Booking_Count
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,...,Launch,Broker,yes,9.212491,18,31679.12,Q1,1,Booked,1
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,...,Under construction,NRI Desk,no,7.723898,106,28284.99,Q2,1,Booked,1
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,...,Ready to move,Direct,yes,6.985493,113,13646.98,Q4,1,Booked,1
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,Ready to move,Online,yes,6.100929,106,15175.01,Q1,1,Booked,1
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4Bhk,15.345392,Secondary,HNI,2024-12-31,...,Under construction,Broker,no,5.312510,18,21471.10,Q4,0,Not Booked,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,Bellary Road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193,Primary,NRI,2023-12-31,...,Under construction,Online,yes,8.378800,109,18351.70,Q4,1,Booked,1
99996,PROP099997,Yelahanka,Project_496,L&T Realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,...,Launch,Broker,yes,7.025209,20,38700.98,Q4,0,Not Booked,0
99997,PROP099998,Rajajinagar,Project_497,Prestige,5599.0,4BHK,13.730179,Primary,Startup Founder,2023-09-30,...,Launch,NRI Desk,yes,8.984990,63,24522.56,Q3,1,Booked,1
99998,PROP099999,Indiranagar,Project_498,Snn Raj,7342.0,4bhk,10.363989,Primary,NRI,2024-09-30,...,Under construction,NRI Desk,yes,7.634717,89,14116.03,Q3,1,Booked,1
99999,PROP100000,Hennur Road,Project_499,Embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,...,Launch,Broker,yes,6.039943,95,20764.79,Q3,1,Booked,1

Project count

In [55]:
df["Project_count"] = 1

In [56]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Price_per_Sqft,Quarter,Booking_Flag,Booking_Status,Booking_Count,Project_count
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,...,Broker,yes,9.212491,18,31679.12,Q1,1,Booked,1,1
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,...,NRI Desk,no,7.723898,106,28284.99,Q2,1,Booked,1,1
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,...,Direct,yes,6.985493,113,13646.98,Q4,1,Booked,1,1
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,Online,yes,6.100929,106,15175.01,Q1,1,Booked,1,1
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4Bhk,15.345392,Secondary,HNI,2024-12-31,...,Broker,no,5.312510,18,21471.10,Q4,0,Not Booked,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,Bellary Road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193,Primary,NRI,2023-12-31,...,Online,yes,8.378800,109,18351.70,Q4,1,Booked,1,1
99996,PROP099997,Yelahanka,Project_496,L&T Realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,...,Broker,yes,7.025209,20,38700.98,Q4,0,Not Booked,0,1
99997,PROP099998,Rajajinagar,Project_497,Prestige,5599.0,4BHK,13.730179,Primary,Startup Founder,2023-09-30,...,NRI Desk,yes,8.984990,63,24522.56,Q3,1,Booked,1,1
99998,PROP099999,Indiranagar,Project_498,Snn Raj,7342.0,4bhk,10.363989,Primary,NRI,2024-09-30,...,NRI Desk,yes,7.634717,89,14116.03,Q3,1,Booked,1,1
99999,PROP100000,Hennur Road,Project_499,Embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,...,Broker,yes,6.039943,95,20764.79,Q3,1,Booked,1,1

In [57]:
df["Project_count"]

0        1
1        1
2        1
3        1
4        1
        ..
99995    1
99996    1
99997    1
99998    1
99999    1
Name: Project_count, Length: 100000, dtype: int64

In [58]:
df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Price_per_Sqft', 'Quarter', 'Booking_Flag',
       'Booking_Status', 'Booking_Count', 'Project_count'],
      dtype='object')

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 23 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  datetime64[ns]
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Price_per_Sqft        100000 non-null  float64
 18  Quarter               100000 non-null  object
 19  Booking_Flag          100000 non-null  int64
 20  Booking_Status        100000 non-null  object
 21  Booking_Count         100000 non-null  int64
 22  Project_count         100000 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(4), object(12)
memory usage: 18.3+ MB

SQL connection

In [60]:
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="houseprice"
)

cursor = connection.cursor()

In [61]:
!pip3 install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\evm88\appdata\local\programs\python\python314\lib\site-packages (2.0.48)
Requirement already satisfied: pymysql in c:\users\evm88\appdata\local\programs\python\python314\lib\site-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in c:\users\evm88\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\evm88\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

SQLAlchemy Engine

In [62]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:12345678@localhost/houseprice"
)

Loading Data into SQL

In [63]:
df.to_sql(
    name="luxury_housing",
    con=engine,
    if_exists="replace",
    index=False
)

100000

Total records

In [64]:
query = """select count(*) 
            from luxury_housing 
"""
cursor.execute(query)
result = cursor.fetchone()

print(result)

(100000,)

Booking Status Count

In [65]:
query = """
SELECT Booking_Status, COUNT(*)
FROM luxury_housing
GROUP BY Booking_Status
"""

cursor.execute(query)

for row in cursor.fetchall():
    print(row)

('Booked', 50013)
('Not Booked', 49987)

Average Price by Developer

In [66]:
query = """ 
SELECT Developer_Name, AVG(Ticket_Price_Cr)
FROM luxury_housing
GROUP BY Developer_Name
"""
cursor.execute(query)

for row in cursor.fetchall():
    print(row[0], ":", round(row[1],2))

Rmz : 12.66
Puravankara : 12.66
Tata Housing : 12.6
Embassy : 12.54
Snn Raj : 12.56
Brigade : 12.54
Prestige : 12.66
Total Environment : 12.75
Godrej : 12.69
L&T Realty : 12.72
Sobha : 12.8